name    'jalli-bind-utils'
version '0.0.1'
source 'http://github.com/jalli/puppet-module-bind-utils'
author 'jalli'
license 'GNU General Public License, Version 3.0'
summary 'Setup bind-utils/dnsutils'
description 'Sets up bind-utils on redhat based systems (Fedora, Centos, RHEL, etc) or dnsutils on debian based systems (Ubuntu, Mint, Debian)'
project_page 'http://github.com/jalli/puppet-module-bind-utils'
